version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Checking files..."
      - # You could run 'npm test' here if you had tests set up

artifacts:
  files:
    - '**/*' # This is CRITICAL. It grabs app.js, public/, package.json, and appspec.yml
  name: BuildArtifact